version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/abdm_app
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=36770136
    networks:
      - springboot-mysql-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=abdm_app
      - MYSQL_ROOT_PASSWORD=36770136
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network

volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network
